/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as AboutIndexImport } from './routes/about/index'
import { Route as AboutVibesIndexImport } from './routes/about/vibes/index'
import { Route as AboutMeIndexImport } from './routes/about/me/index'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AboutIndexRoute = AboutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AboutRoute,
} as any)

const AboutVibesIndexRoute = AboutVibesIndexImport.update({
  id: '/vibes/',
  path: '/vibes/',
  getParentRoute: () => AboutRoute,
} as any)

const AboutMeIndexRoute = AboutMeIndexImport.update({
  id: '/me/',
  path: '/me/',
  getParentRoute: () => AboutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/about/': {
      id: '/about/'
      path: '/'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexImport
      parentRoute: typeof AboutImport
    }
    '/about/me/': {
      id: '/about/me/'
      path: '/me'
      fullPath: '/about/me'
      preLoaderRoute: typeof AboutMeIndexImport
      parentRoute: typeof AboutImport
    }
    '/about/vibes/': {
      id: '/about/vibes/'
      path: '/vibes'
      fullPath: '/about/vibes'
      preLoaderRoute: typeof AboutVibesIndexImport
      parentRoute: typeof AboutImport
    }
  }
}

// Create and export the route tree

interface AboutRouteChildren {
  AboutIndexRoute: typeof AboutIndexRoute
  AboutMeIndexRoute: typeof AboutMeIndexRoute
  AboutVibesIndexRoute: typeof AboutVibesIndexRoute
}

const AboutRouteChildren: AboutRouteChildren = {
  AboutIndexRoute: AboutIndexRoute,
  AboutMeIndexRoute: AboutMeIndexRoute,
  AboutVibesIndexRoute: AboutVibesIndexRoute,
}

const AboutRouteWithChildren = AboutRoute._addFileChildren(AboutRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/about/': typeof AboutIndexRoute
  '/about/me': typeof AboutMeIndexRoute
  '/about/vibes': typeof AboutVibesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutIndexRoute
  '/about/me': typeof AboutMeIndexRoute
  '/about/vibes': typeof AboutVibesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRouteWithChildren
  '/about/': typeof AboutIndexRoute
  '/about/me/': typeof AboutMeIndexRoute
  '/about/vibes/': typeof AboutVibesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/about/' | '/about/me' | '/about/vibes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/about/me' | '/about/vibes'
  id: '__root__' | '/' | '/about' | '/about/' | '/about/me/' | '/about/vibes/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx",
      "children": [
        "/about/",
        "/about/me/",
        "/about/vibes/"
      ]
    },
    "/about/": {
      "filePath": "about/index.tsx",
      "parent": "/about"
    },
    "/about/me/": {
      "filePath": "about/me/index.tsx",
      "parent": "/about"
    },
    "/about/vibes/": {
      "filePath": "about/vibes/index.tsx",
      "parent": "/about"
    }
  }
}
ROUTE_MANIFEST_END */
