name: Deploy GitHub Pages

# see: https://docs.github.com/ja/pages/getting-started-with-github-pages/using-custom-workflows-with-github-pages
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      # needs to actions/github-pages
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup to Using Pages
        uses: actions/configure-pages@v5

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install and Build
        run: corepack enable && pnpm install && pnpm build

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'

      - name: Deploy Artifact to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
